# Generated by Django 5.2.12 on 2026-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug')),
                ('city', models.CharField(default='Tomás Romero Pereira', max_length=120, verbose_name='Ciudad')),
                ('department', models.CharField(default='Itapúa', max_length=120, verbose_name='Departamento')),
                ('address_reference', models.CharField(blank=True, default='Tomás Romero Pereira, Itapúa, Paraguay', max_length=255, verbose_name='Referencia de dirección')),
                ('hero_title', models.CharField(default='Tu próximo lote empieza con una decisión clara', max_length=180, verbose_name='Título principal')),
                ('hero_subtitle', models.TextField(default='Edén Loteamiento presenta una propuesta clara, confiable y fácil de consultar, con ubicación estratégica y contacto directo.', verbose_name='Subtítulo principal')),
                ('description', models.TextField(blank=True, default='Proyecto de loteamiento pensado para comunicar disponibilidad, ubicación y contacto comercial de forma profesional.', verbose_name='Descripción general')),
                ('latitude', models.DecimalField(decimal_places=6, default=-26.494759, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, default=-55.273071, max_digits=9, verbose_name='Longitud')),
                ('map_zoom', models.PositiveSmallIntegerField(default=14, verbose_name='Zoom mapa')),
                ('price_from', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio desde')),
                ('installment_from', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Cuota desde')),
                ('whatsapp_number', models.CharField(blank=True, default='595000000000', max_length=20, verbose_name='WhatsApp')),
                ('contact_email', models.EmailField(blank=True, default='info@example.com', max_length=254, verbose_name='Correo de contacto')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('featured', models.BooleanField(default=True, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['name'],
            },
        ),
    ]
