# Generated by Django 5.2.12 on 2026-03-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20, verbose_name='Manzana')),
                ('number', models.CharField(max_length=20, verbose_name='Lote')),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido')], default='available', max_length=12, verbose_name='Estado')),
                ('price_cash', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Precio contado')),
                ('installment_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de cuotas')),
                ('installment_value', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Valor de cuota')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado en home')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['order', 'block', 'number'],
                'unique_together': {('project', 'block', 'number')},
            },
        ),
    ]
