# Generated by ChatGPT for EdenLoteamiento

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="map_geometry",
            field=models.JSONField(
                blank=True,
                help_text=(
                    "Pega un objeto GeoJSON válido del lote. Se admite un Feature o una Geometry "
                    "(por ejemplo Polygon, MultiPolygon o Point). En GeoJSON el orden de coordenadas "
                    "es [longitud, latitud]."
                ),
                null=True,
                verbose_name="Geometría GeoJSON",
            ),
        ),
    ]